# Generated by Django 6.0.7 on 2026-07-22 03:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(default='ESP32_AI_CAM', help_text='Identifier for the ESP32 unit sending the frame', max_length=50)),
                ('image', models.ImageField(help_text='Path to stored JPEG snapshot on media disk', upload_to='snapshots/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the snapshot was received and saved')),
            ],
            options={
                'verbose_name': 'Security Snapshot',
                'verbose_name_plural': 'Security Snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
