# Generated by Django 6.0.7 on 2026-07-22 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='persons/angles/%Y/%m/')),
                ('angle_label', models.CharField(blank=True, help_text='e.g., front, left_profile, right_45_degree', max_length=50)),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='persons.personofinterest')),
            ],
        ),
    ]
